description "Blakecoin Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BLAKECOIND_BIN="/usr/bin/blakecoind"
env BLAKECOIND_USER="blakecoin"
env BLAKECOIND_GROUP="blakecoin"
env BLAKECOIND_PIDDIR="/var/run/blakecoind"
# upstart can't handle variables constructed with other variables
env BLAKECOIND_PIDFILE="/var/run/blakecoind/blakecoind.pid"
env BLAKECOIND_CONFIGFILE="/etc/blakecoin/blakecoin.conf"
env BLAKECOIND_DATADIR="/var/lib/blakecoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # blakecoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BLAKECOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run blakecoind."
        echo "The setting must appear in $BLAKECOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Blakecoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BLAKECOIND_PIDDIR"
    chmod 0755 "$BLAKECOIND_PIDDIR"
    chown $BLAKECOIND_USER:$BLAKECOIND_GROUP "$BLAKECOIND_PIDDIR"
    chown $BLAKECOIND_USER:$BLAKECOIND_GROUP "$BLAKECOIND_CONFIGFILE"
    chmod 0660 "$BLAKECOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BLAKECOIND_PIDFILE" \
    --chuid $BLAKECOIND_USER:$BLAKECOIND_GROUP \
    --exec "$BLAKECOIND_BIN" \
    -- \
    -pid="$BLAKECOIND_PIDFILE" \
    -conf="$BLAKECOIND_CONFIGFILE" \
    -datadir="$BLAKECOIND_DATADIR" \
    -disablewallet \
    -daemon
